include:
  - services/gateway/compose.yaml
  - services/users/compose.yaml
  - services/auth/compose.yaml

services:
  mongo:
    image: mongo:8
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - backend

  redis:
    image: redis:8
    ports:
      - "6379:6379"
    volumes:
      - redis:/data/redis
    networks:
      - backend

  prometheus:
    image: prom/prometheus:v3.5.0
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    restart: unless-stopped
    networks:
      - backend
  node-exporter:
    image: prom/node-exporter:v1.9.0
    command:
      - "--path.rootfs=/host"
    volumes:
      - "/:/host:ro"
    pid: host
    restart: unless-stopped
    networks:
      - backend
  #
  # postgres:
  #   image: postgres:18
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: api_gateway
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pgdata:/var/lib/postgresql

volumes:
  mongo_data:
  redis:
  prometheus_data:
    # pgdata:

networks:
  backend:
    driver: bridge
