include:
  - services/gateway/compose.yaml
  - services/users/compose.yaml
  - services/auth/compose.yaml

services:
  mongo:
    image: mongo:8
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - backend

  redis:
    image: redis:8
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data/redis
    networks:
      - backend

  # docker run -d --name gateway_prometheus -p 9090:9090 -v $(pwd)/prometheus.local.yml:/etc/prometheus/prometheus.yml prom/prometheus:v3.5.0
  prometheus:
    image: prom/prometheus:v3.5.0
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    restart: unless-stopped
    networks:
      - backend

  # docker run -d --name gateway_node-exporter -p 9100:9100 --pid="host" -v "/:/host:ro" quay.io/prometheus/node-exporter:v1.9.0 --path.rootfs=/host
  node-exporter:
    image: prom/node-exporter:v1.9.0
    command:
      - "--path.rootfs=/host"
    volumes:
      - "/:/host:ro"
    pid: host
    restart: unless-stopped
    networks:
      - backend

  # docker run -d --name gateway_grafana -p 7000:3000 -v $(pwd)/infra/grafana/provisioning-local:/etc/grafana/provisioning -e GF_SECURITY_ADMIN_PASSWORD=admin grafana/grafana
  grafana:
    image: grafana/grafana
    ports:
      - "7000:3000"
    depends_on:
      - prometheus
    volumes:
      - ./infra/grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - backend
  #
  # postgres:
  #   image: postgres:18
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: api_gateway
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pgdata:/var/lib/postgresql

volumes:
  mongo_data:
  redis_data:
  prometheus_data:
  grafana_data:
    # pgdata:

networks:
  backend:
    driver: bridge
