services:
  gateway:
    build:
      context: ..
      target: dev
      args:
        SERVICE_PATH: gateway
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - USERS_SERVICE_URL=http://users-service:3001
      - ORDERS_SERVICE_URL=http://orders-service:3002
    env_file:
      - .env
    depends_on:
      - users-service
      - orders-service
    networks:
      - backend
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/gateway/src
        - action: rebuild
          path: ./package.json
