services:
  gateway:
    build:
      context: ../..
      target: dev
      args:
        SERVICE_PATH: services/gateway
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - USERS_SERVICE_URL=http://users-service:3001
      - AUTH_SERVICE_URL=http://auth-service:3002
      - REDIS_URL=redis://redis:6379/1
    env_file:
      - .env
    depends_on:
      - users-service
      - auth-service
      - redis
    networks:
      - backend
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/services/gateway/src
        - action: rebuild
          path: ./package.json
